# Generated by Django 5.0.6 on 2024-05-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='turno',
            name='turno',
            field=models.CharField(max_length=8),
        ),
    ]
