# Generated by Django 5.0.6 on 2024-05-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_turno_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='profesor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.profesor'),
        ),
    ]
