# Generated by Django 5.0.6 on 2024-05-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_turno_alumnos_remove_turno_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='turno',
        ),
    ]
